version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: credit-jambo-db
    environment:
      POSTGRES_DB: credit_jambo_client
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - credit-jambo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    container_name: credit-jambo-backend
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: credit_jambo_client
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_URL: postgresql://postgres:postgres123@postgres:5432/credit_jambo_client
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - credit-jambo-network
    restart: unless-stopped

  # Frontend (React Native - for development)
  frontend:
    build: ./frontend
    container_name: credit-jambo-frontend
    environment:
      EXPO_PUBLIC_API_URL: http://localhost:4000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - credit-jambo-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  credit-jambo-network:
    driver: bridge
